coverage:
  status:
    project:
      default:
        target: 75% # Require 75% total coverage for the project
        threshold: 0% # No allowable drop in total coverage
        informational: false # Make it blocking (default)
    patch:
      default:
        enabled: false # Disable patch (diff) coverage check
